# dbt_project.yml
name: 'salary_survey'
version: '1.0.0'
config-version: 2

profile: 'salary_survey' # This setting configures which "profile" dbt uses for this project.

model-paths: ["models"]
# analysis-paths: ["analyses"]
# test-paths: ["tests"]
# seed-paths: ["seeds"]
# macro-paths: ["macros"]
# snapshot-paths: ["snapshots"]

# target-path: "dbt/target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  dbt:
    +materialized: table # Sets the default materializations
    +persist_docs: # Writes all of our column descriptions into BigQuery!
      relation: true
      columns: true
    +hours_to_expiration: 168 # for incremental models this does not reset each run

    marts:
      # In reality this would only be useful if we had sub-folders within marts/staging/intermediate
      # but this is an illustration how you would apply a group to a folder
      +group: sales

tests:
  dbt:
    +severity: warn