name: Destroy Infrastructure (Manual)

on:
  workflow_dispatch:  # Manually triggered workflow

jobs:
  destroy:
    runs-on: ubuntu-latest
    
    env:
      TF_VAR_project_id: "software-developer-salaries"
    
    steps:
      # 1. Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.9

      # 3. Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      # 4. Initialize Terraform (remote state)
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=software-developer-salaries-tf-state" \
            -backend-config="prefix=data-analytics-platform-event-driven"
        working-directory: infra

      # 5. Destroy the infrastructure
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: infra