name: Deploy Infrastructure

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      TF_VAR_project_id: "software-developer-salaries"
      REGION: "europe-west9"

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install zip & Zip code
        run: |
          sudo apt-get update
          sudo apt-get install zip -y
          zip ../infra/function-source.zip main.py requirements.txt
          ls -la ../infra/
        working-directory: code

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.9
      
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform Init
        run: |
          terraform init \
            -reconfigure \
            -backend-config="bucket=software-developer-salaries-tf-state" \
            -backend-config="prefix=data-analytics-platform-event-driven"
        working-directory: infra
        
      - name: Debug Terraform Access
        run: |
          echo "Project ID: $TF_VAR_project_id"
          echo "Region: $REGION"  # Fixed typo from TF_VAR_region
          bq ls --project_id=$TF_VAR_project_id
          bq show --format=prettyjson $TF_VAR_project_id:ecommerce
          terraform providers
          terraform import google_bigquery_dataset.ecommerce projects/$TF_VAR_project_id/datasets/ecommerce
        working-directory: infra
        continue-on-error: true  # Allow workflow to proceed for debugging...

      - name: Import Existing Resources
        run: |
          # Check if BigQuery dataset is already in state
          if ! terraform state list | grep -q "google_bigquery_dataset.ecommerce"; then
            if bq ls --project_id=$TF_VAR_project_id | grep -q "ecommerce"; then
              echo "Dataset ecommerce exists but not in state, importing..."
              terraform import google_bigquery_dataset.ecommerce projects/$TF_VAR_project_id/datasets/ecommerce
            else
              echo "Dataset ecommerce does not exist, will be created by Terraform."
            fi
          else
            echo "Dataset ecommerce is already managed by Terraform, skipping import."
          fi
          terraform import google_service_account.function_sa projects/$TF_VAR_project_id/serviceAccounts/gcs-to-bq-trigger@$TF_VAR_project_id.iam.gserviceaccount.com || true
          terraform import google_storage_bucket.gcf_source_bucket $TF_VAR_project_id-gcf-source-bucket || true
          terraform import google_storage_bucket.upload_bucket $TF_VAR_project_id-upload || true
          terraform import google_storage_bucket.archive_bucket $TF_VAR_project_id-archive || true
        working-directory: infra

      - name: Verify Terraform State
        run: terraform state list
        working-directory: infra

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: infra

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: infra