name: Deploy Infrastructure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger in GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: 'zip code'
        name: 'ubuntu:bionic'
        entrypoint: 'sh'
        args: 
          - '-c'
          - | 
            apt-get update; apt install zip -y
            zip /workspace/function-source.zip main.py requirements.txt
        working-directory: code

      - id: 'tf init'
        name: 'hashicorp/terraform:1.3.9'
        entrypoint: 'sh'
        args: 
          - '-c'
          - | 
            terraform init \
            -backend-config="bucket=$PROJECT_ID-tf-state" \
            -backend-config="prefix=data-analytics-platform-event-driven"
        working-directory: infra

      - id: 'tf apply'
        name: 'hashicorp/terraform:1.3.9'
        args: 
          - apply
          - -auto-approve
        working-directory: infra

steps:
- id: 'zip code'
  name: 'ubuntu:bionic'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    apt-get update; apt install zip -y
    zip /workspace/function-source.zip main.py requirements.txt
  dir: code

- id: 'tf init'
  name: 'hashicorp/terraform:1.3.9'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    terraform init \
    -backend-config="bucket=$PROJECT_ID-tf-state" \
    -backend-config="prefix=data-analytics-platform-event-driven"
  dir: infra
- id: 'tf apply'
  name: 'hashicorp/terraform:1.3.9'
  args: 
  - apply
  - -auto-approve
  dir: infra
options:
  env:
    - TF_VAR_project_id=$PROJECT_ID
    - REGION=europe-west9
tags:
  - terraform
  - data-analytics-platform-event-driven
  - apply