name: Upload CSV to GCS

on:
  push:
    paths:
      - 'data/**'
      - '.github/workflows/upload_csv_to_bucket.yaml'
  workflow_dispatch:

jobs:
  upload-csv:
    if: true  # MANUAL disabling of the job
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

    env:
      GCP_PROJECT_ID: ${{ vars.PROJECT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Install gcloud CLI (includes gsutil)
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Upload CSV to GCS upload bucket
        run: |
          BUCKET_NAME="${GCP_PROJECT_ID}-upload"
          TARGET_PATH="surveys/developer_salaries/"
          echo "Uploading CSV to: gs://${BUCKET_NAME}/${TARGET_PATH}"
          gsutil cp data/*.csv gs://${BUCKET_NAME}/${TARGET_PATH}
