name: Upload CSV to GCS

on:
  push:
    paths:
      - 'data/**'
      - '.github/workflows/upload_csv_to_bucket.yaml'

jobs:
  upload-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Upload CSV to GCS
        run: |
          gsutil cp data/*.csv gs://your-etl-trigger-bucket-name/
